#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
# Change into the project's directory
cd "$(dirname "$0")/.."

# Initialize the database
poetry run python -c '''

import asyncio
import asyncpg
import os


def extract(path):
    """Extract the individual SQL statements from a file that contains multiple."""
    with open(path) as file:
        return file.read().split("\n\n\n")


async def initialize():
    """Initialize the database tables, indexes, and constraints."""
    connection = await asyncpg.connect(
        host=os.environ["POSTGRESQL_URL"],
        user=os.environ["POSTGRESQL_IDENTIFIER"],
        password=os.environ["POSTGRESQL_PASSWORD"],
        database=os.environ["POSTGRESQL_DATABASE"],
    )
    for statement in extract("schema.sql"):
        await connection.execute(statement)
    await connection.close()


asyncio.run(initialize())

'''
