#!/usr/bin/env bash

# Safety first
set -o errexit -o pipefail -o nounset
# Change into the project's directory
cd "$(dirname "$0")/.."

# Set our environment variables
export HERMES_ENVIRONMENT="development"
export HERMES_COMMIT_SHA=$(git rev-parse --verify HEAD)
export HERMES_BRANCH_NAME=$(git branch --show-current)
export HERMES_POSTGRESQL_URL="localhost"
export HERMES_POSTGRESQL_PORT="5432"
export HERMES_POSTGRESQL_IDENTIFIER="postgres"
export HERMES_POSTGRESQL_PASSWORD="12345678"
export HERMES_POSTGRESQL_DATABASE="database"
export HERMES_MQTT_URL="localhost"
export HERMES_MQTT_PORT="1883"
export HERMES_MQTT_IDENTIFIER="server"
export HERMES_MQTT_PASSWORD="password"

# Enable importing local modules
export PYTHONPATH=$(pwd)

# Start jupyter server
poetry run python -m jupyterlab --no-browser --port 8533
