#!/bin/sh

# Color definitions
RESTORE='\033[0m'
GREEN='\033[01;32m'

printf "[..] Running black"
# Capture program output in variable
output=$(script -q /dev/null poetry run black --quiet ./app 2>&1 | tr -d '\r' | cat | sed 's/^/  /')
printf "\r${GREEN}[OK]${RESTORE} Running black\n"
# If there's output, print it
[ -z "$output" ] || echo "\n$output\n"

printf "[..] Running ruff"
output=$(script -q /dev/null poetry run ruff --fix ./app 2>&1 | tr -d '\r' | cat | sed 's/^/  /')
printf "\r${GREEN}[OK]${RESTORE} Running ruff\n"
[ -z "$output" ] || echo "\n$output\n"

printf "[..] Running mypy"
output=$(script -q /dev/null poetry run mypy ./app 2>&1 | tr -d '\r' | cat | sed 's/^/  /')
printf "\r${GREEN}[OK]${RESTORE} Running mypy\n"
[ -z "$output" ] || echo "\n$output\n"

printf "[..] Running sqlfluff"
output=$(script -q /dev/null poetry run sqlfluff lint --disable-progress-bar ./app/queries 2>&1 | tr -d '\r' | cat | sed 's/^/  /')
printf "\r${GREEN}[OK]${RESTORE} Running sqlfluff\n"
[ -z "$output" ] || echo "\n$output\n"
