#!/usr/bin/env bash

# Safety first
set -o errexit -o pipefail -o nounset
# Change into the project's directory
cd "$(dirname "$0")/.."

# Build the docker image
./scripts/build ||:

# Create and run the docker container
docker run --env-file .env --publish 8000:8000 --rm server
