#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
# Change into the project's directory
cd "$(dirname "$0")/.."

# Set our environment variables
export ENVIRONMENT="test"
export COMMIT_SHA=$(git rev-parse --verify HEAD)
export BRANCH_NAME=$(git branch --show-current)
export POSTGRESQL_URL="localhost"
export POSTGRESQL_IDENTIFIER="username"
export POSTGRESQL_PASSWORD="12345678"
export POSTGRESQL_DATABASE="database"
export MQTT_URL="localhost"
export MQTT_PORT="1883"
export MQTT_IDENTIFIER="username"
export MQTT_PASSWORD="12345678"

# Path to our Mosquitto configuation
MOSQUITTO_CONFIGURATION="$(pwd)/tests/mosquitto.conf"

# Run PostgreSQL via docker in the background
docker run -td --rm --name postgres -p 5432:5432 -e POSTGRES_USER="$POSTGRESQL_IDENTIFIER" -e POSTGRES_PASSWORD="$POSTGRESQL_PASSWORD" -e POSTGRES_DB="$POSTGRESQL_DATABASE" postgres:14 >/dev/null
# Run the Mosquitto MQTT broker via docker in the background
docker run -td --rm --name mosquitto -p 1883:1883 -v $MOSQUITTO_CONFIGURATION:/mosquitto/config/mosquitto.conf eclipse-mosquitto >/dev/null
# Run the tests
poetry run pytest --cov=app --cov-report=term-missing tests "$@"
# Stop and remove the Mosquitto docker container
docker stop mosquitto >/dev/null
# Stop and remove the PostgreSQL docker container
docker stop postgres >/dev/null
